---
name: Deploy Salt Extension Python Package

on:
  workflow_call:
    inputs:
      test:
        type: boolean
        required: false
        default: true
      version:
        type: string
        required: true
    secrets:
      PYPI_API_TOKEN:
        required: false
      TEST_PYPI_API_TOKEN:
        required: false

jobs:
  build:
    name: Publish Python Package to ${{ ! inputs.test && 'PyPI' || 'Test PyPI' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Download Python Package Artifacts
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806  # v4.1.9
        with:
          name: salt-extension-${{ inputs.version }}-packages
          path: dist

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@7f25271a4aa483500f742f9492b2ab5648d61011  # v1.12.4
        if: ${{ inputs.test }}
        with:
          attestations: false
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Create GitHub Release
        if: ${{ !inputs.test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ inputs.version }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${{ inputs.version }}" \
              --generate-notes \
              dist/*

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@7f25271a4aa483500f742f9492b2ab5648d61011  # v1.12.4
        if: ${{ !inputs.test }}
        with:
          # Attestations are only submitted when using Trusted Publishing,
          # which is triggered by secrets.PYPI_API_TOKEN not being set.
          # They don't work with reusable workflows at the moment.
          # It's related to https://github.com/pypi/warehouse/issues/11096
          attestations: false
          password: ${{ secrets.PYPI_API_TOKEN }}
