---
on:
  workflow_call:
    outputs:
      changed-files:
        description: "Changed file JSON output from dorny/paths-filter"
        value: ${{ jobs.get-changed-files.outputs.changed-files }}

jobs:
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-24.04
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      changed-files: ${{ toJSON(steps.changed-files.outputs) }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Get Changed Files
        id: changed-files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          token: ${{ github.token }}
          list-files: escape
          filters: |
            repo:
              - added|modified:
                - '**'
            deleted:
              - deleted:
                - '**'
            pre-commit:
              - added|modified|deleted:
                - .pre-commit-hooks/**
                - .pre-commit-config.y?(a)ml
                - .pylintrc
                - pyproject.toml
            # If files in this filter change, a test release to TestPyPI
            # should be attempted. This is currently not implemented yet.
            release:
              - added|modified|deleted:
                - .copier-answers.y?(a)ml
                - .github/workflows/**
                - CHANGELOG.md
                - pyproject.toml
                - setup.py

      - name: Echo Changed Files Output
        run: echo "${{ toJSON(steps.changed-files.outputs) }}"
