---
name: Pull Request or Push

on:
  push:
    branches:
      - 'main'  # Run on pushes to main
    tags-ignore:
      - '*'   # Ignore pushes to tags
  pull_request:

jobs:
  call_central_workflow:
    name: CI
    uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
    with:
      deploy-docs: true
    permissions:
      contents: write
      id-token: write
      pages: write
      pull-requests: read
